// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package Greeter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	ServerStreamSayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_ServerStreamSayHelloClient, error)
	ClientStreamSayHello(ctx context.Context, opts ...grpc.CallOption) (Greeter_ClientStreamSayHelloClient, error)
	BothStreamSayHello(ctx context.Context, opts ...grpc.CallOption) (Greeter_BothStreamSayHelloClient, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/grpctest_proto.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) ServerStreamSayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_ServerStreamSayHelloClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[0], "/grpctest_proto.Greeter/ServerStreamSayHello", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterServerStreamSayHelloClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_ServerStreamSayHelloClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterServerStreamSayHelloClient struct {
	grpc.ClientStream
}

func (x *greeterServerStreamSayHelloClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) ClientStreamSayHello(ctx context.Context, opts ...grpc.CallOption) (Greeter_ClientStreamSayHelloClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[1], "/grpctest_proto.Greeter/ClientStreamSayHello", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterClientStreamSayHelloClient{stream}
	return x, nil
}

type Greeter_ClientStreamSayHelloClient interface {
	Send(*HelloRequest) error
	CloseAndRecv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterClientStreamSayHelloClient struct {
	grpc.ClientStream
}

func (x *greeterClientStreamSayHelloClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterClientStreamSayHelloClient) CloseAndRecv() (*HelloReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) BothStreamSayHello(ctx context.Context, opts ...grpc.CallOption) (Greeter_BothStreamSayHelloClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[2], "/grpctest_proto.Greeter/BothStreamSayHello", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterBothStreamSayHelloClient{stream}
	return x, nil
}

type Greeter_BothStreamSayHelloClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterBothStreamSayHelloClient struct {
	grpc.ClientStream
}

func (x *greeterBothStreamSayHelloClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterBothStreamSayHelloClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	ServerStreamSayHello(*HelloRequest, Greeter_ServerStreamSayHelloServer) error
	ClientStreamSayHello(Greeter_ClientStreamSayHelloServer) error
	BothStreamSayHello(Greeter_BothStreamSayHelloServer) error
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeterServer) ServerStreamSayHello(*HelloRequest, Greeter_ServerStreamSayHelloServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerStreamSayHello not implemented")
}
func (UnimplementedGreeterServer) ClientStreamSayHello(Greeter_ClientStreamSayHelloServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientStreamSayHello not implemented")
}
func (UnimplementedGreeterServer) BothStreamSayHello(Greeter_BothStreamSayHelloServer) error {
	return status.Errorf(codes.Unimplemented, "method BothStreamSayHello not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpctest_proto.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_ServerStreamSayHello_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).ServerStreamSayHello(m, &greeterServerStreamSayHelloServer{stream})
}

type Greeter_ServerStreamSayHelloServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterServerStreamSayHelloServer struct {
	grpc.ServerStream
}

func (x *greeterServerStreamSayHelloServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_ClientStreamSayHello_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).ClientStreamSayHello(&greeterClientStreamSayHelloServer{stream})
}

type Greeter_ClientStreamSayHelloServer interface {
	SendAndClose(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterClientStreamSayHelloServer struct {
	grpc.ServerStream
}

func (x *greeterClientStreamSayHelloServer) SendAndClose(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterClientStreamSayHelloServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Greeter_BothStreamSayHello_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).BothStreamSayHello(&greeterBothStreamSayHelloServer{stream})
}

type Greeter_BothStreamSayHelloServer interface {
	Send(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterBothStreamSayHelloServer struct {
	grpc.ServerStream
}

func (x *greeterBothStreamSayHelloServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterBothStreamSayHelloServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpctest_proto.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStreamSayHello",
			Handler:       _Greeter_ServerStreamSayHello_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientStreamSayHello",
			Handler:       _Greeter_ClientStreamSayHello_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BothStreamSayHello",
			Handler:       _Greeter_BothStreamSayHello_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "greeter.proto",
}
